# Generated by Django 4.2.9 on 2024-09-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "cupón", "verbose_name_plural": "cupones"},
        ),
    ]
