# Generated by Django 4.2.9 on 2024-09-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="fist_name",
            new_name="first_name",
        ),
    ]
